Lab 1
AlexBossov/WebProgramming pull request #1
Opened 2022-09-22 17:47 UTC by AlexBossov

2022-09-22 17:53 UTC, Gvozdoslav requested changes
Давай давай нападай на мои rem мистер em

2022-09-22 17:53 UTC, Gvozdoslav commented on src/css/outlines.css
> +    line-height: 3em;
Почему использовал em, а не rem?

2022-09-23 05:53 UTC, AlexBossov commented on src/css/outlines.css
> +    line-height: 3em;
Понял, поменял на rem

2022-09-23 05:54 UTC, iakuliaev requested changes
в целом норм, но не хватает ридмишки

2022-09-23 05:54 UTC, iakuliaev commented on src/html/index.html
> +<html lang="en">
по условию лабы, язык - РУССКИЙ!!!!!

2022-09-23 05:55 UTC, AlexBossov commented on src/html/index.html
> +<html lang="en">
Ой, не заметил, понял

2022-09-23 05:58 UTC, iakuliaev approved these changes
Молодец, лови апрув

2022-09-23 06:00 UTC, Gvozdoslav requested changes

2022-09-23 06:00 UTC, Gvozdoslav commented on src/html/index.html
> +    <title>LabTrade</title>
change title on Russian

2022-09-23 06:00 UTC, AlexBossov commented on src/html/index.html
> +    <title>LabTrade</title>
окей, понял

2022-09-23 06:03 UTC, Gvozdoslav approved these changes

2022-09-23 06:17 UTC, merged